/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annuaire.view;

import java.awt.Cursor;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

import annuaire.AppAnnuaire;
import annuaire.util.Contact;
import annuaire.util.DAO;
import annuaire.util.ResultSetTableModel;

public class Details extends JPanel {

	private static final long serialVersionUID = 1L;
    private JButton annuler;
    private JLabel codePostalLab;
    private JTextField codePostalText;
    private JLabel emailLab;
    private JTextField emailText;
    private JLabel imageLabel;
    private JLabel nomLab;
    private JTextField nomText;
    private JLabel prenomLab;
    private JTextField prenomText;
    private JButton sauvegarder;
    private JLabel telLab;
    private JTextField teleText;
    private JLabel villeLab;
    private JTextField villeText;
    private int id;
    private DAO bdd = new DAO();;
    private ResultSetTableModel model;
    private final static String SAVEGARDER_ACTION = "Sauvegarder";
    private final static String RECHERCHER_ACTION = "Trouver";
    /**
     * Creates new form Details
     */
    public Details() {
        initComponents();
    }
	/**
     * Creates new form Details
     */
    public Details(Contact pContact) {
        initComponents();
        if(pContact != null)
        {
        	id = pContact.getId();
            nomText.setText(pContact.getNom());
            prenomText.setText(pContact.getPrenom());
            emailText.setText(pContact.getEmail());
            teleText.setText(pContact.getTelephone());
            villeText.setText(pContact.getVille());
            codePostalText.setText(pContact.getCodePostal());
        }
    }

    public JButton getSauvegarde()
    {
        return sauvegarder;
    }
    
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        nomLab = new JLabel();
        nomText = new JTextField();
        prenomLab = new JLabel();
        prenomText = new JTextField();
        telLab = new JLabel();
        teleText = new JTextField();
        emailLab = new JLabel();
        emailText = new JTextField();
        villeLab = new JLabel();
        villeText = new JTextField();
        codePostalLab = new JLabel();
        codePostalText = new JTextField();
        annuler = new JButton();
        sauvegarder = new JButton(); 
        imageLabel = new JLabel();

        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(833, 572));
        
        nomLab.setText("Nom");
        prenomLab.setText("Prénom");
        telLab.setText("Téléphone");
        emailLab.setText("E-mail");
        villeLab.setText("Ville");
        codePostalLab.setText("Code postal");

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        sauvegarder.setText("Sauvegarder");
        sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderActionPerformed(evt);
            }
        });

        imageLabel.setIcon(new ImageIcon(getClass().getResource("/annuaire/annuaire_entreprises_aeroport.jpg"))); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(imageLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(telLab)
                    .addComponent(nomLab)
                    .addComponent(villeLab))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(emailText, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(villeText, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(codePostalLab))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomText, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prenomLab))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teleText, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailLab)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(codePostalText, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prenomText, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)))))
                .addGap(221, 221, 221))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(annuler)
                .addGap(18, 18, 18)
                .addComponent(sauvegarder, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomLab)
                    .addComponent(nomText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomLab))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(teleText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(telLab)
                    .addComponent(emailText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLab))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(villeText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(villeLab)
                    .addComponent(codePostalText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(codePostalLab))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(sauvegarder)
                    .addComponent(annuler))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(imageLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        AppAnnuaire.app.getContentPane().removeAll(); 
        AppAnnuaire.app.setContentPane(new Results(null)); 
        AppAnnuaire.app.setVisible(true); 

    }//GEN-LAST:event_annulerActionPerformed

    private void sauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderActionPerformed
        AppAnnuaire.app.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
    	AppAnnuaire.app.getContentPane().removeAll(); 
        Contact contact = new Contact();
        contact.setId(id); 
        contact.setNom(nomText.getText());
        contact.setPrenom(prenomText.getText());
        contact.setTelephone(teleText.getText());
        contact.setEmail(emailText.getText());
        contact.setVille(villeText.getText());
        contact.setCodePostal(codePostalText.getText());

        if(SAVEGARDER_ACTION.equalsIgnoreCase(sauvegarder.getText()))
		{ 
        	bdd.saveOrUpdateContact(contact);
        	model = bdd.getAllContacts();
		}
        else if(RECHERCHER_ACTION.equalsIgnoreCase(sauvegarder.getText()))
        {
        	model = bdd.searchAvance(contact);
        }
        AppAnnuaire.app.setContentPane(new Results(model)); 
        AppAnnuaire.app.setVisible(true); 
        AppAnnuaire.app.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)); 

    }//GEN-LAST:event_sauvegarderActionPerformed

}
