/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annuaire.view;

import java.awt.Cursor;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

import annuaire.AppAnnuaire;
import annuaire.util.DAO;
import annuaire.util.Error;

import com.sun.jmx.snmp.tasks.Task;


/**
 *
 * @author Mostapha
 */
public class Login extends JPanel {

    /**
     * Creates new form Login
     */
	//GEN-LAST:event_entrerBoutonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton entrerBouton;
    private JLabel error;
    private JLabel errorLogin;
    private JLabel errorPassword;
    private JLabel identifiantLab;
    private JTextField identifiantText;
    private JLabel image;
    private JLabel jLabel1;
    private JLabel passwordLab;
    private JPasswordField passwordText;
    private DAO bdd = new DAO();
    // End of variables declaration//GEN-END:variables
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        image = new JLabel();
        identifiantLab = new JLabel();
        passwordLab = new JLabel();
        identifiantText = new JTextField();
        passwordText = new JPasswordField();
        errorLogin = new JLabel();
        errorPassword = new JLabel();
        entrerBouton = new JButton();
        error = new JLabel();
        jLabel1 = new JLabel();

        setPreferredSize(new java.awt.Dimension(690, 500));

        image.setIcon(new ImageIcon(getClass().getResource("/annuaire/annuaire2.jpg"))); // NOI18N

        identifiantLab.setText("Identifiant");

        passwordLab.setText("Mot de passe");

        errorLogin.setForeground(new java.awt.Color(255, 0, 0));

        errorPassword.setForeground(new java.awt.Color(255, 0, 0));

        entrerBouton.setText("Entrer");
        entrerBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrerBoutonActionPerformed(evt);
            }
        });

        error.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/annuaire/1419826133_2-128.png"))); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(image)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLab)
                            .addComponent(identifiantLab))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(passwordText, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(entrerBouton, GroupLayout.Alignment.TRAILING))
                                    .addComponent(identifiantText, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(errorPassword, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(errorLogin, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(error, GroupLayout.PREFERRED_SIZE, 450, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(image, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(identifiantLab)
                            .addComponent(identifiantText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorLogin, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLab)
                            .addComponent(passwordText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorPassword))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(error)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entrerBouton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }

    private void entrerBoutonActionPerformed(java.awt.event.ActionEvent evt) {
    	Error.setErrorMessage("");
    	error.setText("");
    	errorLogin.setText("");
    	errorPassword.setText("");
    	
       if(identifiantText.getText() == null  || identifiantText.getText().trim().equals("") )
       {
           errorLogin.setText("Saisissez votre identifiant.");
       }
       else if(passwordText.getText() == null  || passwordText.getText().trim().equals("") )
       {
           errorPassword.setText("Saisissez votre mot de passe.");
       }
       else
       {
           entrerBouton.setEnabled(false);
           AppAnnuaire.app.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
    	   boolean retourLogin = bdd.login(identifiantText.getText(), passwordText.getText());
    	   if(Error.getErrorMessage() != null 
    			   && !Error.getErrorMessage().trim().equalsIgnoreCase(""))
    	   {
    		   JOptionPane.showMessageDialog(null,
    				    Error.getErrorMessage(),
    				    "Error",
    				    JOptionPane.ERROR_MESSAGE);
    	   }
    	   else if(!retourLogin)
    	   {
    		   error.setText("L'identifient ou le mot de passe saisi est incorrect.");
    	   }
    	   else
    	   {
               AppAnnuaire.app.getContentPane().removeAll(); 
               AppAnnuaire.app.setContentPane(new Results()); 
               AppAnnuaire.app.setSize(844, 625); 
               AppAnnuaire.app.getMenuApp().setVisible(true); 
               AppAnnuaire.app.setVisible(true); 
    	   }
    	   entrerBouton.setEnabled(true);
           AppAnnuaire.app.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)); 

       }
    }
}
